package Forms;
import dbconecciones.dbconection;
import static dbconecciones.dbconection.getconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author rosad
 */
public class EditProductsForm extends javax.swing.JFrame {

    
    
    dbconection conex = new dbconection();  //Instanciando coneccion 
    
    //Declarando elementos necesarios para la coneccion.
    Connection conected;
    DefaultTableModel model;
    Statement state;
    ResultSet rset;    
    PreparedStatement pst;
    
    
    public EditProductsForm() {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana al ejecutarse permaneza en el centro de la pantalla.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtbrand = new javax.swing.JTextField();
        txtcategory = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Amount");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Brand");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Category");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Price");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 150, -1));
        jPanel2.add(txtbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 150, -1));
        jPanel2.add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 150, -1));
        jPanel2.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));
        jPanel2.add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, -1));

        btnupdate.setBackground(new java.awt.Color(153, 255, 204));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nuevo.png"))); // NOI18N
        btnupdate.setText("SAVE");
        btnupdate.setBorder(null);
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 90, 30));

        btnback.setBackground(new java.awt.Color(153, 255, 204));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atras.png"))); // NOI18N
        btnback.setBorder(null);
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel2.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        btndelete.setBackground(new java.awt.Color(153, 255, 204));
        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eliminar.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.setBorder(null);
        btndelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        this.dispose();   //Cierra el formulario actual.
        ProductsForm productform = new ProductsForm();
        productform.setVisible(true);   //Llamar el formulario de la tabla productos (ProductsForm).
    }//GEN-LAST:event_btnbackActionPerformed

    //Boton para actualizar o editar productos.
    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       
       
       save();  //Llamando metodo para editar o actualizar un producto.
         
    }//GEN-LAST:event_btnupdateActionPerformed
    //Boton Eliminar productos.
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       
        Connection  conect = null;
        try {
            conect = getconnect();
            pst = conect.prepareStatement("Delete from products WHERE Nombre=?"); //Query para eliminar producto de la tabla y base de datos.
            pst.setString(1, txtname.getText());
            int res = pst.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Datos Eliminados"); //Cuadro de dialogo
                
                this.dispose();   //Cerrar formulario actual.
                ProductsForm productform = new ProductsForm();      
                productform.setVisible(true);    //Llamar el formulario de la tabla productos (ProductsForm).
            }
        } catch (Exception e) {
        }
           
    }//GEN-LAST:event_btndeleteActionPerformed
     //Metodo para editar o actualizar un producto.
    void save(){
          
       //Declaracion de variables.
       
      String nombre = txtname.getText();
      String marca = txtbrand.getText();
      String categoria = txtcategory.getText();
      String precio = txtprice.getText();
      String cantidad = txtamount.getText();
      
          try {
              //Condicion para que detectar campos nulos o vacios.
              if(nombre.equals("") || marca.equals("") || categoria.equals("") || precio.equals("") || cantidad.equals("")){
                  JOptionPane.showMessageDialog(null, "Faltan datos por ingresar.");
                                    
              }
              
              else{
                            //Query para actualizar o editar un producto.
              String sql = "Update products set Nombre='" +nombre+ "', Marca='" +marca+ "', Categoria='" +categoria+ "', Precio='" +precio+"', Cantidad_Dispo='" +cantidad+"' where Nombre='"+nombre+"'";
              conected = conex.getconnect(); //Instanciando el metodo de la coneccion de la base de datos (dbconection).
              state = conected.createStatement();
              state.executeUpdate(sql);
              JOptionPane.showMessageDialog(null, "Datos Modificiados.");  //Cuadro de dialogo.
              
              this.dispose();            //Cerrar formulario actual.
              ProductsForm productform = new ProductsForm();
              productform.setVisible(true);   //Llamar el formulario de la tabla productos (ProductsForm).
                             
              }
          } catch (Exception e) {
              
              
          }
      
      
      
      }
      
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProductsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txtamount;
    public static javax.swing.JTextField txtbrand;
    public static javax.swing.JTextField txtcategory;
    public static javax.swing.JTextField txtname;
    public static javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables

    
}
