/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import javax.swing.JOptionPane;

/**
 *
 * @author rosad
 */
public class PrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initComponents();
        setLocationRelativeTo(null); //Para que la ventana al ejecutarse permaneza en el centro de la pantalla.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnusers = new javax.swing.JButton();
        btnproductos = new javax.swing.JButton();
        btncerrarsesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnusers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/usuarios.png"))); // NOI18N
        btnusers.setText("USERS");
        btnusers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusersActionPerformed(evt);
            }
        });
        jPanel1.add(btnusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 190, 80));

        btnproductos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/products.png"))); // NOI18N
        btnproductos.setText("PRODUCTS");
        btnproductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 190, 80));

        btncerrarsesion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cerrar-sesion.png"))); // NOI18N
        btncerrarsesion.setText("LOG OUT");
        btncerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(btncerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, 80));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/principal.png"))); // NOI18N
        jLabel1.setText("MAIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 210, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarsesionActionPerformed
      
         loginform logform = new loginform(); //Instanciando formulario del login (loginform).
       
         //Condicion de confirmacion de cerrar sesion.
        if(JOptionPane.showConfirmDialog(null, "¿Estas seguro que quieres cerrar sesion?", "Confirmacion", JOptionPane.YES_NO_OPTION)==0){
            this.dispose();   //Cerrar formulario actual
            logform.setVisible(true);  //Llamar al formulario del login (loginform).
        }
        
        
        
    }//GEN-LAST:event_btncerrarsesionActionPerformed

    private void btnusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusersActionPerformed
        
        this.dispose();   //Cerrar formulario actual
        UsersRegisters usersregisters = new UsersRegisters();
        usersregisters.setVisible(true);    //Llamar al formulario de los usuarios registrados (UsersRegisters).
        
    }//GEN-LAST:event_btnusersActionPerformed

    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed
        
        this.dispose();         //Cerrar formulario actual
        ProductsForm productform = new ProductsForm();
        productform.setVisible(true);       //Llamar al formulario de la tabla producto (ProductsForm).
       
    }//GEN-LAST:event_btnproductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrarsesion;
    private javax.swing.JButton btnproductos;
    private javax.swing.JButton btnusers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
