package Forms;

import dbconecciones.dbconection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Forms.EditProductsForm;
import classes.Products;
import mant.ProductsManage;

/**
 *
 * @author rosad
 */
public class ProductsForm extends javax.swing.JFrame {

    dbconection conex = new dbconection();      //Instanciando coneccion de la base de datos
    
    //Declarando elementos necesarios para la coneccion.
    Connection conected;
    DefaultTableModel model;
    Statement state;
    ResultSet rset;
    int  hi;
    PreparedStatement pst;
    
    
    public ProductsForm() {
        initComponents();
        setLocationRelativeTo(null);   //Para que la ventana al ejecutarse permaneza en el centro de la pantalla.
        mostrarentablaproducto();     //Llamando metodo mostrarentablaproducto para mostrar los productos registrados en la base de datos.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        btncreate = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Marca", "Categoria", "Precio", "Cantidad_Dispo"
            }
        ));
        producttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producttableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                producttableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(producttable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 650, 230));

        btncreate.setBackground(new java.awt.Color(153, 255, 204));
        btncreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nuevo.png"))); // NOI18N
        btncreate.setText("CREATE");
        btncreate.setBorder(null);
        btncreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel1.add(btncreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 130, 50));

        btnback.setBackground(new java.awt.Color(153, 255, 204));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/atras.png"))); // NOI18N
        btnback.setBorder(null);
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        btnlogout.setBackground(new java.awt.Color(153, 255, 204));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cerrar-sesion.png"))); // NOI18N
        btnlogout.setBorder(null);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 40, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/producto logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 320, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        
        loginform logform = new loginform();
       
        //Condicion de confirmacion de cerrar sesion.
        if(JOptionPane.showConfirmDialog(null, "¿Estas seguro que quieres cerrar sesion?", "Confirmacion", JOptionPane.YES_NO_OPTION)==0){
            
            this.dispose();     //Cerrar formulario actual.
            logform.setVisible(true);       //Llamar formulario del login.
        }
        
        
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        
        this.dispose();  //Cerrar formulario actual.
        PrincipalForm principalform = new PrincipalForm();
        principalform.setVisible(true);   //Llamar formulario principal (PrincipalForm)
        
    }//GEN-LAST:event_btnbackActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        
        this.dispose();     //Cerrar formulario actual.
        CreateProductsForm createproductform = new CreateProductsForm();
        createproductform.setVisible(true);  //Llamar formulario de crear o añadir nuevo producto (CreateProductsForm)
    }//GEN-LAST:event_btncreateActionPerformed
    
    //Evento para cuando seleccione un producto aparezcan en el formulario editar productos o eliminar productos (EditProductsForm)
    private void producttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseClicked
        
        
        int fila = producttable.getSelectedRow(); //Variable para el numero de filas
        
        //Condicion para detectar si no hay filas seleccionadas.
        if (fila == -1){
            
            JOptionPane.showMessageDialog(null, "No se selecciono ninguna fila");
        
        }else{
            this.dispose();   //Cierra formulario Actual
            EditProductsForm editproductform = new EditProductsForm();
            editproductform.setVisible(true);  //Llama el formulario editar o eliminar productos (EditProductsForm)
             
            //Declarion de variables y asignacion de posiciones 
           String nombre = (String) producttable.getValueAt(fila, 0);
           String marca = (String) producttable.getValueAt(fila, 1);
           String categoria = (String) producttable.getValueAt(fila, 2);
           String precio = (String) producttable.getValueAt(fila, 3);
           String cantidad = (String) producttable.getValueAt(fila, 4);
           
           //Asignando valores.
           EditProductsForm.txtname.setText(nombre);
           EditProductsForm.txtbrand.setText(marca);
           EditProductsForm.txtcategory.setText(categoria);
           EditProductsForm.txtprice.setText(precio);
           EditProductsForm.txtamount.setText(cantidad);
                            
        }
        
             
    }//GEN-LAST:event_producttableMouseClicked

    private void producttableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_producttableMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsForm().setVisible(true);
            }
        });
        
        
    }
    //Metodo para mostrar registros de la base de datos a la tabla productos
     void mostrarentablaproducto(){

        String sql = "select * from products";  //Query para mostrar en tabla productos (productstable)
        
        try {
            conected = conex.getconnect();  //Instanciando metodo de conexion de la base de datos (dbconection)
            state = conected.createStatement();
            rset = state.executeQuery(sql);  //Executando el query de la base de datos.
            Object[] data = new Object[5];   //Objeto de tipo arreglo o array.   
            model = (DefaultTableModel) producttable.getModel();
            
            //Condicion para mostrar los datos de la base de datos en la tabla productos (producttable)
            while(rset.next()){
                                       
                data [0] = rset.getString("Nombre");
                data [1] = rset.getString("Marca");
                data [2] = rset.getString("Categoria");
                data [3] = rset.getString("Precio");
                data [4] = rset.getString("Cantidad_Dispo");              
                model.addRow(data);
                
            }
            producttable.setModel(model);
        } catch (Exception e) {
        }
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btnlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable producttable;
    // End of variables declaration//GEN-END:variables
}

